In [1]:
import numpy as np
import sys

In [2]:
import numpy as np

array_1D = np.array([1,2,3])   # An array (length 3)
                               # Which has a shape of (3,) (3 entries)

array_2D = np.array([[1,2,3,4,5],    # An array (length 2) of arrays (length 5)
                     [6,7,8,9,10]])  # Which has a shape of (2, 5) 
                                     # 2 entries with 5 entries each

array_3D = np.array([[[1,2,3],  # An array (length 2) of arrays (length 3)
                      [4,5,6],  # of arrays (length 3)
                      [7,8,9]], # Which has a shape of (2, 3, 3)
                                # 2 entries with 3 entries each with 3 entries each
                     [[9,8,7],
                      [6,5,4],
                      [3,2,1]]])


In [3]:
import time

array_size = 1000000

In [4]:
# Generating the list
my_list = [i for i in range(array_size)]

# Defining the starting time
start_time_list = time.time()

for i in range(array_size):   # For each element in the list
    my_list[i] += 3           # add 3 to it

# Printing the overall time taken to compute
print("List Speed: " + str(time.time() - start_time_list))

List Speed: 0.3312969207763672


In [5]:
# Generating the array
my_array = np.arange(array_size)

# Defining the starting time
start_time_array = time.time()

# Adding 3 to every term (Look at how easy it is!)
my_array += 3

# Printing the overall time taken to compute
print("Array Speed: " + str(time.time() - start_time_array))

Array Speed: 0.0009443759918212891


In [6]:
my_3by3 = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

my_1by3 = np.array([0,1,2])

my_3by3 += my_1by3

print(my_3by3)

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [7]:
my_list = [i for i in range(1000)]
my_array = np.array([i for i in range(1000)])

list_size = sys.getsizeof(my_list)
array_size = sys.getsizeof(my_array)

print(f"List Size: {str(list_size)} bytes")
print(f"Array Size: {str(array_size)} bytes")

List Size: 9016 bytes
Array Size: 4096 bytes


In [8]:
int8_array = np.arange(100, dtype = "int8")   # Output range: -127 to 127
print(sys.getsizeof(int8_array))

int16_array = np.arange(100, dtype = "int16")
print(sys.getsizeof(int16_array))

int32_array = np.arange(100, dtype = "int32")
print(sys.getsizeof(int32_array))

196
296
496


In [9]:
array_2D = np.array([[1,2,3,4,5],    # An array (length 2) of arrays (length 5)
                     [6,7,8,9,10]])  

shape = array_2D.shape
print(f"Shape: {shape}")             # Which has a shape of (2, 5) 


Shape: (2, 5)


In [10]:
# An array from a certain shape
shape = (2, 3, 3)
empty_array = np.empty(shape)    # Creates an array with specifying entries
zeros_array = np.zeros(shape)    # Creates an array of zeros from a shape
ones_array = np.ones(shape)      # Creates an array of ones from a shape
 
fill_value = 3
filled_array = np.full(shape, fill_value)  # Creates an array of a value from a shape

# An array from numerical ranges
start = 1
stop = 100
step = 4
num = 10

range_array = np.arange(start, stop, step)      # Creates evenly spaced entries
linspace_array = np.linspace(start, stop, num)  # Creates evenly spaced entries
logspace_array = np.logspace(start, stop, num)  # Creates log-spaced entries

In [12]:
array_3D = np.array([[[1,2,3],  # An array (length 2) of arrays (length 3)
                      [4,5,6],  # of arrays (length 3)
                      [7,8,9]], # Which has a shape of (2, 3, 3)
                                # 2 entries with 3 entries each with 3 entries each
                     [[9,8,7],
                      [6,5,4],
                      [3,2,1]]])

print(array_3D.max(axis = 0))   # Look at each element of each 3 by 3, and find the max

[[9 8 7]
 [6 5 6]
 [7 8 9]]
